# Generated by Django 4.2.5 on 2023-09-30 15:40

from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(help_text='Введите имя автора', max_length=100, primary_key=True, serialize=False, verbose_name='Имя')),
                ('language', models.CharField(blank=True, help_text='Введите язык, который использует автор для своих книг', max_length=100, null=True, verbose_name='Язык')),
                ('birth_date', models.DateField()),
                ('biography', models.TextField(blank=True, help_text='Расскажите немного о жизни автора', null=True, verbose_name='Биография')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название жанра', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание жанра', null=True, verbose_name='Описание')),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=100, verbose_name='Название')),
                ('publication_year', models.IntegerField(help_text='Введите год публикации', validators=[test_django.models.validate_number_length], verbose_name='Год публикации')),
                ('description', models.TextField(help_text='Добавьте описание книги', verbose_name='Описание')),
                ('author', models.ForeignKey(help_text='Выберите жанр', on_delete=django.db.models.deletion.CASCADE, to='test_django.author', verbose_name='Жанр')),
                ('genres', models.ManyToManyField(to='test_django.genre')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
