# Generated by Django 4.2.5 on 2023-10-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Расскажите немного о жизни автора', null=True, verbose_name='Об авторе'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора', to='test_django.author', verbose_name='Автор'),
        ),
    ]
