# Generated by Django 4.2.5 on 2023-10-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0003_critic_review_reader_favoritebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritebook',
            name='book',
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='reader',
            field=models.ForeignKey(blank=True, help_text='Выберите читателя', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_django.reader', verbose_name='id читателя'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='book',
            field=models.ManyToManyField(blank=True, help_text='Выберите книги', null=True, to='test_django.book'),
        ),
    ]
