# Generated by Django 4.2.5 on 2023-10-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0004_remove_favoritebook_book_alter_favoritebook_reader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebook',
            name='book',
            field=models.ManyToManyField(help_text='Выберите книги', to='test_django.book'),
        ),
    ]
