# Generated by Django 4.2.5 on 2023-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0005_alter_favoritebook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='critic',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='critic',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='reader',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
