# Generated by Django 4.2.5 on 2023-11-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0007_alter_reader_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('A', 'Автор'), ('B', 'Книга')], max_length=1, verbose_name='Тип заявки')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('book_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название книги')),
            ],
            options={
                'db_table': 'User Request',
            },
        ),
    ]
